name = "file60-worker"
main = "worker/src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2"
bucket_name = "file60-files"
preview_bucket_name = "file60-files-preview"

[vars]
JWT_SECRET = "dev-secret-key"
